### ISSUE TITLE
KeyError: 'photos'

### ISSUE THREAD

**Issue by ZakirJaafar** [ze-kel/DayOne-JSON-to-MD#2]
Unsure if the script completed the function fully. I can see some folders created but the terminal displayed this:

Traceback (most recent call last):
  File "/Users/zakirjaafar/Downloads/temp 3 DayOne-JSON-to-MD-main/app.py", line 175, in <module>
    ProcessZips(inpath, outpath)
  File "/Users/zakirjaafar/Downloads/temp 3 DayOne-JSON-to-MD-main/app.py", line 166, in ProcessZips
    processJson("temp/" + zipnameClean + "/" + jsonname  ,jsonnameClean, zipnameClean, outpath)
  File "/Users/zakirjaafar/Downloads/temp 3 DayOne-JSON-to-MD-main/app.py", line 98, in processJson
    momentIn = entry['photos']
KeyError: 'photos'

Anything I should check with the file output?

**Comment by illkle** [comment]
Try this branch, it should work.
https://github.com/ze-kel/DayOne-JSON-to-MD/tree/issue-2

Although the error implies that you have some media type in your entries that my script doesn't support. You might get a better result using [one of the forks](https://github.com/ze-kel/DayOne-JSON-to-MD/network/members), where some people significantly improved on my code.
